// - LOGIN
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN = 'LOGIN';
export const LOGIN_START = 'LOGIN_START';
export const LOGOUT = 'LOGOUT';
export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN';
export const SET_BOOTSTRAP_STATUS = 'SET_BOOTSTRAP_STATUS';
//APPLICATION
export const CHANGE_THEME = 'CHANGE_THEME';
export const CHANGE_FONT = 'CHANGE_FONT';
export const FORCE_APPEARANCE = 'FORCE_APPEARANCE';
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
//TRIPS
export const SET_SELECTED_TRIP = 'SET_SELECTED_TRIP';
export const CLEAR_SELECTED_TRIP = 'CLEAR_SELECTED_TRIP';
//CONNECTIVITY
export const CHECK_HEALTH_START = 'CHECK_HEALTH_START';
export const CHECK_HEALTH_SUCCESS = 'CHECK_HEALTH_SUCCESS';
export const CHECK_HEALTH_FAILURE = 'CHECK_HEALTH_FAILURE';
export const RESET_CONNECTIVITY = 'RESET_CONNECTIVITY'; 