import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  container: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    width: '100%',
    marginTop: 0,
  },
  imageBackground: {
    width: '100%',
    opacity: 1.0
  },
  overlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    padding: 20,
  },
  logoContainer: {
    position: 'absolute',
    top: 25,
    left: 20,
    alignItems: 'center',
    zIndex: 9999,  
  },
  logo: {
    width: 180,
    height: 50,
    marginBottom: 5,
    marginTop: 20, 
  },
  profileButton: {
    position: 'absolute',
    top: 40,
    right: 20,
    zIndex: 9999,
    padding: 10,
  },
  profileButtonInner: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  centerSquareContainer: {
    position: 'absolute',
    top: '50%',
    left: '53%',
    transform: [{ translateX: -78 }, { translateY: -78 }],
    width: 156,
    height: 156,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
    marginTop: 100,
    display: 'none',
  },
  centerSquareImage: {
    width: 156,
    height: 156,
    borderRadius: 20,
  },
  roundedRectangle: {
    position: 'absolute',
    top: 30,
    left: 0,
    right: 0,
    height: 120,
    zIndex: 1,
    marginHorizontal: 10,
    flexDirection: 'row',
  },
  roundedRectangleBackground: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#1b302a',
    borderRadius: 20,
    opacity: 0.5,
    borderColor: '#0b1713',
    borderWidth: 1,
  },
  leftPanel: {
    flex: 7,
    height: '100%', 
    padding: 15,
    justifyContent: 'center',
    zIndex: 2,
  },
  locationText: {
    color: '#FFFFFF',
    fontSize: 30,
    fontWeight: '700',
    marginBottom: 8,
    textShadowColor: 'rgba(0, 0, 0, 0.5)',
    textShadowOffset: { width: 0.5, height: 0.5 },
    textShadowRadius: 1,
    opacity: 1,
  },
  tripText: {
    color: '#FFFFFF',
    fontSize: 24,
    fontWeight: '600',
    textShadowColor: 'rgba(0, 0, 0, 0.5)',
    textShadowOffset: { width: 0.5, height: 0.5 },
    textShadowRadius: 1,
    opacity: 1,
  },
  rightPanel: {
    flex: 3,
    height: '100%',
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  rightPanelBackground: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#000000',
    opacity: 0.5,
  },
  numberText: {
    fontSize: 42,
    fontWeight: '700',
    color: '#FFFFFF',
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0.5, height: 0.5 },
    textShadowRadius: 1,
    zIndex: 2,
  },
  unitText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0.5, height: 0.5 },
    textShadowRadius: 1,
    marginTop: 2,
    zIndex: 2,
  },
}); 